apiVersion: v1
kind: Secret
metadata:
  name: go-assistant-secrets
  namespace: go-assistant
type: Opaque
data:
  NOTION_API_KEY: Y2hhbmdlbWU=
  GMAIL_CLIENT_ID: Y2hhbmdlbWU=
  GMAIL_CLIENT_SECRET: Y2hhbmdlbWU=
  GOOGLE_CALENDAR_ID: Y2hhbmdlbWU=
  OPENAI_API_KEY: Y2hhbmdlbWU=
  NOTION_DATABASE_ID: Y2hhbmdlbWU=
